runtime: python27
api_version: 1
threadsafe: yes

handlers:

#new handlers should go ABOVE the catch all url (.*)
- url: /static
static_dir: static
- url: .*
#regular expression
script: main.app

- url: /test


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
